Si = cell(4,4);
Sim = cell(4,4);
Sia = cell(4,4);
for i = 1:4
	for j = 1:4
		if j == i
			continue;
		end
		k = 1:4;
		k = find(k!=i&k!=j);
		Si(i,j) = cross( ...
			cell2mat(Ne(i,j,k(1)))-cell2mat(Na(i,j)), ...
			cell2mat(Ne(i,j,k(2)))-cell2mat(Na(i,j)), ...
			2)/2 + cross( ...
			cell2mat(Ne(i,j,k(2)))-Ng, ...
			cell2mat(Ne(i,j,k(1)))-Ng, ...
			2)/2;
		Si(i,j) = (1 - 2*(dot(cell2mat(Si(i,j)),cell2mat(Na(i,j))-[N(E(:,i),1) N(E(:,i),2) N(E(:,i),3)],2)<0)).*cell2mat(Si(i,j));
		Sim(i,j) = [
			mean( ...
				[
					cell2mat(Ne(i,j,k(1)))(:,1), ...
					cell2mat(Ne(i,j,k(2)))(:,1)
				], 2), ...
			mean( ...
				[
					cell2mat(Ne(i,j,k(1)))(:,2), ...
					cell2mat(Ne(i,j,k(2)))(:,2)
				], 2), ...
			mean( ...
				[
					cell2mat(Ne(i,j,k(1)))(:,3), ...
					cell2mat(Ne(i,j,k(2)))(:,3)
				], 2)
		];
		Sia(i,j) = sqrt(
			dot(
				cell2mat(Si(i,j)), ...
				cell2mat(Si(i,j)), ...
				2)
			);
	end
end