plot( ...
	N(E(1,1),1), ...
	N(E(1,1),2), ...
	N(E(1,1),3), ...
	'marker', '*', ...
	'linestyle', 'none');

plot( ...
	N(E(1,2),1), ...
	N(E(1,2),2), ...
	N(E(1,2),3), ...
	'marker', '*', ...
	'linestyle', 'none');

plot( ...
	N(E(1,3),1), ...
	N(E(1,3),2), ...
	N(E(1,3),3), ...
	'marker', '*', ...
	'linestyle', 'none');

plot( ...
	N(E(1,1),4), ...
	N(E(1,1),4), ...
	N(E(1,1),4), ...
	'marker', '*', ...
	'linestyle', 'none');

Se