if ischar(idxE)
  if strcmp(idxE, 'all')
    idx = 1:rows(E);
  end
else
  idx = idxE;
end

idxN = unique(E(idx,:)(:));

scatter3(N(idxN,1), N(idxN,2), N(idxN,3), [], 'b', 'marker', '*', 'displayname', 'Nodes');
for i = idxN'
	text(N(i,1), N(i,2), N(i,3), ['  ', num2str(i)]);
end

##for i = 1:length(BC)
##	BCi = BC(i);
##	plot3( ...
##		N(BCi.targets,1), ...
##		N(BCi.targets,2), ...
##		N(BCi.targets,3), ...
##		'marker', 'o', ...
##		'linestyle', 'none', ...
##		'displayname', strjoin({BCi.type, ' ',num2str(BCi.value)}, ''));
##	text( ...
##		median(N(BCi.targets,1)), ...
##		median(N(BCi.targets,2)), ...
##		median(N(BCi.targets,3)), ...
##		[BCi.type, ' ', num2str(BCi.value)]);
##end