##((program.analysis.U-min(program.analysis.U))/(max(program.analysis.U)-min(program.analysis.U)))
scatter3(program.analysis.Nodes(:,1), program.analysis.Nodes(:,2), program.analysis.Nodes(:,3), [], program.analysis.U, 'marker', '*', 'displayname', 'Nodes');
for i = 1:length(program.analysis.Nodes)
	text(program.analysis.Nodes(i,1), program.analysis.Nodes(i,2), program.analysis.Nodes(i,3), [' ', num2str(program.analysis.U(i))]);
end

##for i = 1:length(BC)
##	BCi = BC(i);
##	if strcmp(BCi.type, 'TEMPERATURE')
##		scatter3( ...
##			program.analysis.Nodes(BCi.targets,1), ...
##			program.analysis.Nodes(BCi.targets,2), ...
##			program.analysis.Nodes(BCi.targets,3), ...
##			[], ...
##			BCi.value, ...
##			'marker', 'o', ...
##			'displayname', strjoin({'Temperature ',num2str(BCi.value)}, ''));
##		text( ...
##			median(program.analysis.Nodes(BCi.targets,1)), ...
##			median(program.analysis.Nodes(BCi.targets,2)), ...
##			median(program.analysis.Nodes(BCi.targets,3)), ...
##			num2str(BCi.value));
##	end
##end

colormap(jet);
colorbar;
legend;