if ischar(idxE)
  if strcmp(idxE, 'all')
    idx = 1:rows(program.analysis.ElementNodeIds);
  end
else
  idx = idxE;
end

idxN = unique(program.analysis.ElementNodeIds(idx,:)(:));

scatter3(program.analysis.Nodes(idxN,1), program.analysis.Nodes(idxN,2), program.analysis.Nodes(idxN,3), [], 'b', 'marker', '*', 'displayname', 'Nodes');
for i = idxN'
	text(program.analysis.Nodes(i,1), program.analysis.Nodes(i,2), program.analysis.Nodes(i,3), ['  ', num2str(i)]);
end

##for i = 1:length(BC)
##	BCi = BC(i);
##	plot3( ...
##		program.analysis.Nodes(BCi.targets,1), ...
##		program.analysis.Nodes(BCi.targets,2), ...
##		program.analysis.Nodes(BCi.targets,3), ...
##		'marker', 'o', ...
##		'linestyle', 'none', ...
##		'displayname', strjoin({BCi.type, ' ',num2str(BCi.value)}, ''));
##	text( ...
##		median(program.analysis.Nodes(BCi.targets,1)), ...
##		median(program.analysis.Nodes(BCi.targets,2)), ...
##		median(program.analysis.Nodes(BCi.targets,3)), ...
##		[BCi.type, ' ', num2str(BCi.value)]);
##end